// <auto-generated />
using System;
using FashionM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519194121_CuentasPorCobrar")]
    partial class CuentasPorCobrar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionM.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FashionM.Models.Clientes", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("ActividadEconomica")
                        .HasColumnType("numeric");

                    b.Property<string>("Agente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FashionM.Models.CuentaPorCobrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("FashionM.Models.CuentaPorCobrarPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaPorCobrarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoRecibo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPorCobrarId");

                    b.ToTable("CuentasPorCobrarPagos");
                });

            modelBuilder.Entity("FashionM.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadEco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Agentes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CedulaJuridica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CuentaBAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuentaBCR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuentaBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SimpeMovil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InventarioCodigo")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("FashionM.Models.HistorialInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("text");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HistorialInventarios");
                });

            modelBuilder.Entity("FashionM.Models.ImagenZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZapatoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoId");

                    b.ToTable("ImagenesZapato");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCabys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProveedorCatalogoId")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.HasIndex("ProveedorCatalogoId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("FashionM.Models.MovimientoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("MovimientoInventarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoInventarioId");

                    b.ToTable("MovimientosDetalle");
                });

            modelBuilder.Entity("FashionM.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("FashionM.Models.NotaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteVenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Año")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<decimal>("DescuentoGlobal")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalDevuelto")
                        .HasColumnType("numeric");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("VentaId");

                    b.ToTable("NotasCredito");
                });

            modelBuilder.Entity("FashionM.Models.NotaCreditoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDevuelta")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadOriginal")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DescuentoLinea")
                        .HasColumnType("numeric");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotaCreditoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCorregido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioOriginal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VentaDetalleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaCreditoId");

                    b.HasIndex("VentaDetalleId");

                    b.ToTable("NotaCreditoDetalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agente")
                        .HasColumnType("text");

                    b.Property<bool>("AprobadoSecretaria")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Empresa")
                        .HasColumnType("text");

                    b.Property<int>("EstadoCredito")
                        .HasColumnType("integer");

                    b.Property<bool>("EstadoEntrega")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FirmaBodega")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("PedidosCliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<bool>("Entregado")
                        .HasColumnType("boolean");

                    b.Property<int>("PedidoClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorCatalogoId")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoClienteId");

                    b.HasIndex("ProveedorCatalogoId");

                    b.ToTable("PedidoClienteDetalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGenerado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PedidosMain");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PedidoMainId")
                        .HasColumnType("integer");

                    b.Property<int>("ProveedorCatalogoId")
                        .HasColumnType("integer");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoMainId");

                    b.HasIndex("ProveedorCatalogoId");

                    b.ToTable("PedidosProveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedorDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("PedidoProveedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoProveedorId");

                    b.ToTable("PedidosProveedorDetalle");
                });

            modelBuilder.Entity("FashionM.Models.Proforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteVenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("FacturadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCajas")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.HasIndex("EmpresaId", "Numero")
                        .IsUnique();

                    b.ToTable("Proformas");
                });

            modelBuilder.Entity("FashionM.Models.ProformaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProformaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.HasIndex("ProformaId");

                    b.ToTable("ProformaDetalles");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ColorZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZapatoProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoProveedorId");

                    b.ToTable("ColoresZapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.DetalleZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZapatoProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoProveedorId");

                    b.ToTable("DetallesZapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ProveedorCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadEconomica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProveedoresCatalogo");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.SuelaZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZapatoProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoProveedorId");

                    b.ToTable("SuelasZapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.TallaZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioColombia")
                        .HasColumnType("numeric");

                    b.Property<int>("ZapatoProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoProveedorId");

                    b.ToTable("TallasZapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ZapatoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecioColombia")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<int>("ProveedorCatalogoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorCatalogoId");

                    b.ToTable("ZapatosProveedor");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("Actividad")
                        .HasColumnType("numeric");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("Cedula");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("TallasInventario");
                });

            modelBuilder.Entity("FashionM.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteVenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Año")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacturadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCajas")
                        .HasColumnType("integer");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FashionM.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Suela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorCedula");

                    b.ToTable("Zapatos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FashionM.Models.CuentaPorCobrar", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany("CuentasPorCobrar")
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Venta", "Venta")
                        .WithOne("CuentaPorCobrar")
                        .HasForeignKey("FashionM.Models.CuentaPorCobrar", "VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FashionM.Models.CuentaPorCobrarPago", b =>
                {
                    b.HasOne("FashionM.Models.CuentaPorCobrar", "CuentaPorCobrar")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaPorCobrarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaPorCobrar");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Fotos")
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.ImagenZapato", b =>
                {
                    b.HasOne("FashionM.Models.Zapato", "Zapato")
                        .WithMany("Imagenes")
                        .HasForeignKey("ZapatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ProveedorCatalogo", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCatalogoId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.MovimientoDetalle", b =>
                {
                    b.HasOne("FashionM.Models.MovimientoInventario", "MovimientoInventario")
                        .WithMany("Detalles")
                        .HasForeignKey("MovimientoInventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovimientoInventario");
                });

            modelBuilder.Entity("FashionM.Models.MovimientoInventario", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.NotaCredito", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Venta", "Venta")
                        .WithMany("NotasCredito")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FashionM.Models.NotaCreditoDetalle", b =>
                {
                    b.HasOne("FashionM.Models.NotaCredito", "NotaCredito")
                        .WithMany("Detalles")
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.VentaDetalle", "VentaDetalle")
                        .WithMany("NotasCreditoDetalle")
                        .HasForeignKey("VentaDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NotaCredito");

                    b.Navigation("VentaDetalle");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.HasOne("FashionM.Models.PedidoCliente", "PedidoCliente")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Provedor.ProveedorCatalogo", "ProveedorCatalogo")
                        .WithMany()
                        .HasForeignKey("ProveedorCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PedidoCliente");

                    b.Navigation("ProveedorCatalogo");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.HasOne("FashionM.Models.PedidoMain", null)
                        .WithMany("PedidosProveedor")
                        .HasForeignKey("PedidoMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Provedor.ProveedorCatalogo", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedorDetalle", b =>
                {
                    b.HasOne("FashionM.Models.PedidoProveedor", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionM.Models.Proforma", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Empresa", "Empresa")
                        .WithMany("Proformas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FashionM.Models.ProformaDetalle", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", null)
                        .WithMany()
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Proforma", "Proforma")
                        .WithMany("Detalles")
                        .HasForeignKey("ProformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proforma");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ColorZapato", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ZapatoProveedor", "Zapato")
                        .WithMany("Colores")
                        .HasForeignKey("ZapatoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.DetalleZapato", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ZapatoProveedor", "Zapato")
                        .WithMany("Detalles")
                        .HasForeignKey("ZapatoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.SuelaZapato", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ZapatoProveedor", "Zapato")
                        .WithMany("Suelas")
                        .HasForeignKey("ZapatoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.TallaZapato", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ZapatoProveedor", "Zapato")
                        .WithMany("Tallas")
                        .HasForeignKey("ZapatoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ZapatoProveedor", b =>
                {
                    b.HasOne("FashionM.Models.Provedor.ProveedorCatalogo", "Proveedor")
                        .WithMany("Zapatos")
                        .HasForeignKey("ProveedorCatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Tallas")
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.Venta", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("FashionM.Models.VentaDetalle", b =>
                {
                    b.HasOne("FashionM.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.HasOne("FashionM.Models.Proveedor", "Proveedor")
                        .WithMany("Zapatos")
                        .HasForeignKey("ProveedorCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FashionM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FashionM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FashionM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionM.Models.Clientes", b =>
                {
                    b.Navigation("CuentasPorCobrar");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FashionM.Models.CuentaPorCobrar", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FashionM.Models.Empresa", b =>
                {
                    b.Navigation("Proformas");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("FashionM.Models.MovimientoInventario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.NotaCredito", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoMain", b =>
                {
                    b.Navigation("PedidosProveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.Proforma", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ProveedorCatalogo", b =>
                {
                    b.Navigation("Zapatos");
                });

            modelBuilder.Entity("FashionM.Models.Provedor.ZapatoProveedor", b =>
                {
                    b.Navigation("Colores");

                    b.Navigation("Detalles");

                    b.Navigation("Suelas");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Navigation("Zapatos");
                });

            modelBuilder.Entity("FashionM.Models.Venta", b =>
                {
                    b.Navigation("CuentaPorCobrar");

                    b.Navigation("Detalles");

                    b.Navigation("NotasCredito");
                });

            modelBuilder.Entity("FashionM.Models.VentaDetalle", b =>
                {
                    b.Navigation("NotasCreditoDetalle");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
