// <auto-generated />
using System;
using FashionM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311140035_AddDetallePedidoProveedor")]
    partial class AddDetallePedidoProveedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionM.Models.Clientes", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("ActividadEconomica")
                        .HasColumnType("numeric");

                    b.Property<string>("Agente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InventarioCodigo")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("FashionM.Models.ImagenZapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZapatoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZapatoId");

                    b.ToTable("ImagenesZapato");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCabys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Empresa")
                        .HasColumnType("text");

                    b.Property<int>("EstadoCredito")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FirmaBodega")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("PedidosCliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("PedidoClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoClienteId");

                    b.HasIndex("ProveedorCedula");

                    b.ToTable("PedidoClienteDetalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGenerado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PedidosMain");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PedidoMainId")
                        .HasColumnType("integer");

                    b.Property<int>("ProveedorCedula")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoMainId");

                    b.HasIndex("ProveedorCedula");

                    b.ToTable("PedidosProveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedorDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("PedidoProveedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoProveedorId");

                    b.ToTable("PedidosProveedorDetalle");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("Actividad")
                        .HasColumnType("numeric");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("Cedula");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("InventarioCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("TallasInventario");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProveedorCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Suela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorCedula");

                    b.ToTable("Zapatos");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Fotos")
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.ImagenZapato", b =>
                {
                    b.HasOne("FashionM.Models.Zapato", "Zapato")
                        .WithMany("Imagenes")
                        .HasForeignKey("ZapatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.HasOne("FashionM.Models.PedidoCliente", "PedidoCliente")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCedula")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PedidoCliente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.HasOne("FashionM.Models.PedidoMain", null)
                        .WithMany("PedidosProveedor")
                        .HasForeignKey("PedidoMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionM.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedorDetalle", b =>
                {
                    b.HasOne("FashionM.Models.PedidoProveedor", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Tallas")
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.HasOne("FashionM.Models.Proveedor", "Proveedor")
                        .WithMany("Zapatos")
                        .HasForeignKey("ProveedorCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.Clientes", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.PedidoMain", b =>
                {
                    b.Navigation("PedidosProveedor");
                });

            modelBuilder.Entity("FashionM.Models.PedidoProveedor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Navigation("Zapatos");
                });

            modelBuilder.Entity("FashionM.Models.Zapato", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
