// <auto-generated />
using System;
using FashionM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302185927_Proveedores")]
    partial class Proveedores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionM.Models.Clientes", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("ActividadEconomica")
                        .HasColumnType("numeric");

                    b.Property<string>("Agente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FashionM.Models.Codigo", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodigo"));

                    b.Property<string>("NombreCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProveedorCedula")
                        .HasColumnType("integer");

                    b.HasKey("IdCodigo");

                    b.HasIndex("ProveedorCedula");

                    b.ToTable("Codigos");
                });

            modelBuilder.Entity("FashionM.Models.Color", b =>
                {
                    b.Property<int>("IdColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdColor"));

                    b.Property<int>("CodigoId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdColor");

                    b.HasIndex("CodigoId");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCabys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteCedula")
                        .HasColumnType("integer");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoCredito")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FirmaBodega")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("PedidosCliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidoClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoClienteId");

                    b.ToTable("PedidoClienteDetalles");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<decimal>("Actividad")
                        .HasColumnType("numeric");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("IDTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("Cedula");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("FashionM.Models.Suela", b =>
                {
                    b.Property<int>("IdSuela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuela"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoSuela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSuela");

                    b.HasIndex("ColorId");

                    b.ToTable("Suelas");
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("InventarioCodigo")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventarioCodigo");

                    b.ToTable("TallasInventario");
                });

            modelBuilder.Entity("FashionM.Models.Codigo", b =>
                {
                    b.HasOne("FashionM.Models.Proveedor", "Proveedor")
                        .WithMany("Codigos")
                        .HasForeignKey("ProveedorCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("FashionM.Models.Color", b =>
                {
                    b.HasOne("FashionM.Models.Codigo", "Codigo")
                        .WithMany("Colores")
                        .HasForeignKey("CodigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codigo");
                });

            modelBuilder.Entity("FashionM.Models.Foto", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Fotos")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.HasOne("FashionM.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FashionM.Models.PedidoClienteDetalle", b =>
                {
                    b.HasOne("FashionM.Models.PedidoCliente", "PedidoCliente")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoCliente");
                });

            modelBuilder.Entity("FashionM.Models.Suela", b =>
                {
                    b.HasOne("FashionM.Models.Color", "Color")
                        .WithMany("Suelas")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("FashionM.Models.TallaInventario", b =>
                {
                    b.HasOne("FashionM.Models.Inventario", "Inventario")
                        .WithMany("Tallas")
                        .HasForeignKey("InventarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("FashionM.Models.Codigo", b =>
                {
                    b.Navigation("Colores");
                });

            modelBuilder.Entity("FashionM.Models.Color", b =>
                {
                    b.Navigation("Suelas");
                });

            modelBuilder.Entity("FashionM.Models.Inventario", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("FashionM.Models.PedidoCliente", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FashionM.Models.Proveedor", b =>
                {
                    b.Navigation("Codigos");
                });
#pragma warning restore 612, 618
        }
    }
}
